# Build stage
FROM golang:1.25-alpine AS builder

WORKDIR /app

# Install git (kadang dibutuhin dependency)
RUN apk add --no-cache git

# Copy dependency dulu (biar cache kepake)
COPY go.mod go.sum ./
RUN go mod download

# Copy semua source code
COPY . .

# Build binary
RUN CGO_ENABLED=0 GOOS=linux go build -o main .

# Run stage
FROM alpine:latest

WORKDIR /root/

COPY --from=builder /app/main .
COPY --from=builder /app/database ./database

EXPOSE 3000

CMD ["./main"]